services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: my_database
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
